# Generated by Django 3.1.4 on 2020-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
