# Generated by Django 3.1.4 on 2020-12-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20201226_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='p_type',
            field=models.CharField(choices=[('webapp', 'webapp'), ('website', 'website'), ('card', 'card')], default='webapp', max_length=50),
        ),
    ]
